### ISSUE TITLE
Shortcut actions don't show in Shortcuts app

### ISSUE THREAD

**Issue by theoccurrence** [PoomSmart/TrollLEDs#5]
Unfortunately the new Shortcut actions don't show for me in the Shortcuts app.
I've tried the sandboxed and unsandboxed version of 1.4.0 with system as well as with user registration, killed the Shortcuts app and resprung a couple of times. I don't know if I'm missing something, but the Shortcuts actions of another app I installed with Trollstore show up fine (TrollCuts).

![image](https://github.com/PoomSmart/TrollLEDs/assets/16444679/2cd5799c-805e-4e61-ad2b-45fce947ebf9)
![image](https://github.com/PoomSmart/TrollLEDs/assets/16444679/ad1c63e7-61a1-4f0f-8e4b-6836faf46284)
![image](https://github.com/PoomSmart/TrollLEDs/assets/16444679/b2493e5b-03d9-4ee8-bc3b-97401ede42ec)
![image](https://github.com/PoomSmart/TrollLEDs/assets/16444679/f14d0ab2-30e7-4cc1-a0b5-0b3f6897347b)

**Comment by augustobob** [comment]
You're misunderstanding Trollcuts and trollleds, the shortcut added to the app is the 3d touch shortcuts.

![IMG_1636](https://github.com/PoomSmart/TrollLEDs/assets/41238825/9a6f7625-eaca-4e4e-a625-9df6dad453b8)

**Comment by PoomSmart** [comment]
@augustobob is right, but maybe it's also interesting to add the shortcuts to Shortcuts app. I'll take a look when I have time.

**Comment by PoomSmart** [comment]
However, it may happen in a distant future. To achieve your request, this project must be converted to Swift, which I don't plan to anytime soon.

**Comment by theoccurrence** [comment]
> @augustobob is right, but maybe it's also interesting to add the shortcuts to Shortcuts app. I'll take a look when I have time.

I see, there was a bit of confusion when I made this Issue https://github.com/PoomSmart/TrollLEDs/issues/4 and talked about "Shortcut actions".

As someone who does a lot with Shortcuts, I'd not only call this "maybe interesting", it makes an app like this so much more usable.

If I wanted to use the amber light instead of the normal flashlight, with a Shortcut action I could just set it to double tap the back of my device or something. Having to open the app, or to go to the homescreen to invoke the 3D Touch menu is always more steps than what would be possible with a Shortcuts integration, especially now where Activator doesn't work anymore.

I hope you consider this, even if it's apparently a lot of work. Of course I can't speak for everyone, but for me this would multiply the usability of this app.

**Comment by augustobob** [comment]
If PS create a "personal default" option to start the app with, and/or add buttons into the app aside from the sliders it would be just two steps to enable your personal flashlight. Slide to unlock and touch the app (assuming Its on your home screen)

Enviado do meu iPhone

Em 23 de jan. de 2024, à(s) 14:10, theoccurrence ***@***.***> escreveu:

﻿

@augustobob<https://github.com/augustobob> is right, but maybe it's also interesting to add the shortcuts to Shortcuts app. I'll take a look when I have time.

I see, there was a bit of confusion when I made this Issue #4<https://github.com/PoomSmart/TrollLEDs/issues/4> and talked about "Shortcut actions".

As someone who does a lot with Shortcuts, I'd not only call this "maybe interesting", it makes an app like this so much more usable.

If I wanted to use the amber light instead of the normal flashlight, with a Shortcut action I could just set it to double tap the back of my device or something. Having to open the app, or to go to the homescreen to invoke the 3D Touch menu is always more steps than what would be possible with a Shortcuts integration, especially now where Activator doesn't work anymore.

I hope you consider this, even if it's apparently a lot of work. Of course I can't speak for everyone, but for me this would multiply the usability of this app.

**Comment by PoomSmart** [comment]
@theoccurrence 
> Also the 3DTouch amber shortcut sets both warm LEDs to 255, but it's a brighter (and in my opinion better) amber light if you just set Warm LED 0 to 255, not both.

What device are you testing TrollLEDs on?

**Comment by theoccurrence** [comment]
> What device are you testing TrollLEDs on?

iPhone 12 Pro Max iOS 16.4

**Comment by theoccurrence** [comment]
> If PS create a "personal default" option to start the app with, and/or add buttons into the app aside from the sliders it would be just two steps to enable your personal flashlight.

The app pretty much already has "buttons". Just click on one of these to set the coresponding LED automatically to 255. That's how I'm using the app already.

Having a "personal default" that activates instantly on opening the app is a great idea tho, which would solve the use case of a quick customized flashlight at least, because you can easily open any app you'd like with an already existing stock shortcuts action. It's a tad bit annoying still that it has to open the app, and there's no "return to previous location" shortcuts action, but it still would be a major improvement to efficiency.

**Comment by PoomSmart** [comment]
@theoccurrence It affects only shortcut menus, not in-app.

**Comment by theoccurrence** [comment]
> @theoccurrence It affects only shortcut menus, not in-app.

Oh, I'm sorry. Works as intended.

**Comment by PoomSmart** [comment]
Implemented in v1.7.0

**Comment by theoccurrence** [comment]
> Implemented in v1.7.0

Thank you very much, this makes the app much more useful for me 😊
